### ISSUE TITLE
"edison-cli deploy" returns "TypeError: Object #<Object> has no method 'clearFolder'"

### ISSUE THREAD

**Issue by landlessness** [zettajs/edison-cli#3]
When trying to deploy to the Edison with `edison-cli` I encounter the error below and the command seems to hang. Not sure if it's actually hung or installing like it's supposed to do.

Command:

``` bash
> edison-cli -H 10.1.10.51 deploy
```

Error:

``` bash
edison-cli -H 10.1.10.51 deploy
XDK - IoT App Dameon v0.0.13 - commands: run, list, debug, status
uncaughtException occured: TypeError: Object #<Object> has no method 'clearFolder'
    at /opt/xdk-daemon/current/appDaemon.js:229:19
    at Object.oncomplete (fs.js:107:15)
```

**Comment by AdamMagaluk** [comment]
The setup on some of the edisons did not complete properly. You need to run the steps in the email i sent you Sunday. Ssh into the edison and run the following commands. https://gist.github.com/AdamMagaluk/79c3badae8ff0e2fff9d

**Comment by landlessness** [comment]
I spent a couple hours today updating all the edisons. i will try again.

**Comment by landlessness** [comment]
I ran it all again. same `clearFolder` issue.

**Comment by AdamMagaluk** [comment]
Double check the contents of `/opt/xdk-daemon/current/daemonUtils.js` on the Edison it should export `clearFolder` function at the bottom of the file.

**Comment by AdamMagaluk** [comment]
Ahh, make sure you reboot or unplug and plug it back in. The error your getting is part of a Node.js daemon running on the device you updated the file but haven't restarted the application.

**Comment by landlessness** [comment]
this is on the bottom:

``` js
module.exports = {
  clearFolder:clearFolder,
  unzip:unzip
};
```

**Comment by landlessness** [comment]
will try reboot (again)
