### ISSUE TITLE
Error: bind EADDRINUSE 224.0.0.251:5353

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/edison-cli#8]
```
λ: edison-cli list
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 224.0.0.251:5353
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at dgram.js:213:18
    at doNTCallback3 (node.js:450:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by exsilium** [comment]
Just ran into this myself. This is due to an issue in outdated mdns-js package used by edison-cli. mdns-js/node-mdns-js#31. Just call a newer version from the package.json:

`"mdns-js": "^0.5.0",`
